/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.webtown.liferay.portlet.reference.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ResourcedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedGroupedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Reference service. Represents a row in the &quot;Reference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.webtown.liferay.portlet.reference.model.impl.ReferenceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.webtown.liferay.portlet.reference.model.impl.ReferenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Reference
 * @see hu.webtown.liferay.portlet.reference.model.impl.ReferenceImpl
 * @see hu.webtown.liferay.portlet.reference.model.impl.ReferenceModelImpl
 * @generated
 */
@ProviderType
public interface ReferenceModel extends BaseModel<Reference>, ResourcedModel,
	ShardedModel, StagedGroupedModel, TrashedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reference model instance should use the {@link Reference} interface instead.
	 */

	/**
	 * Returns the primary key of this reference.
	 *
	 * @return the primary key of this reference
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reference.
	 *
	 * @param primaryKey the primary key of this reference
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this reference.
	 *
	 * @return the uuid of this reference
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this reference.
	 *
	 * @param uuid the uuid of this reference
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this reference.
	 *
	 * @return the ID of this reference
	 */
	public long getId();

	/**
	 * Sets the ID of this reference.
	 *
	 * @param id the ID of this reference
	 */
	public void setId(long id);

	/**
	 * Returns the resource prim key of this reference.
	 *
	 * @return the resource prim key of this reference
	 */
	@Override
	public long getResourcePrimKey();

	/**
	 * Sets the resource prim key of this reference.
	 *
	 * @param resourcePrimKey the resource prim key of this reference
	 */
	@Override
	public void setResourcePrimKey(long resourcePrimKey);

	@Override
	public boolean isResourceMain();

	/**
	 * Returns the group ID of this reference.
	 *
	 * @return the group ID of this reference
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this reference.
	 *
	 * @param groupId the group ID of this reference
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this reference.
	 *
	 * @return the company ID of this reference
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this reference.
	 *
	 * @param companyId the company ID of this reference
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this reference.
	 *
	 * @return the user ID of this reference
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this reference.
	 *
	 * @param userId the user ID of this reference
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this reference.
	 *
	 * @return the user uuid of this reference
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this reference.
	 *
	 * @param userUuid the user uuid of this reference
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this reference.
	 *
	 * @return the user name of this reference
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this reference.
	 *
	 * @param userName the user name of this reference
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this reference.
	 *
	 * @return the create date of this reference
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this reference.
	 *
	 * @param createDate the create date of this reference
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this reference.
	 *
	 * @return the modified date of this reference
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this reference.
	 *
	 * @param modifiedDate the modified date of this reference
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the reference ID of this reference.
	 *
	 * @return the reference ID of this reference
	 */
	@AutoEscape
	public String getReferenceId();

	/**
	 * Sets the reference ID of this reference.
	 *
	 * @param referenceId the reference ID of this reference
	 */
	public void setReferenceId(String referenceId);

	/**
	 * Returns the version of this reference.
	 *
	 * @return the version of this reference
	 */
	public double getVersion();

	/**
	 * Sets the version of this reference.
	 *
	 * @param version the version of this reference
	 */
	public void setVersion(double version);

	/**
	 * Returns the name of this reference.
	 *
	 * @return the name of this reference
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this reference.
	 *
	 * @param name the name of this reference
	 */
	public void setName(String name);

	/**
	 * Returns the url title of this reference.
	 *
	 * @return the url title of this reference
	 */
	@AutoEscape
	public String getUrlTitle();

	/**
	 * Sets the url title of this reference.
	 *
	 * @param urlTitle the url title of this reference
	 */
	public void setUrlTitle(String urlTitle);

	/**
	 * Returns the short description of this reference.
	 *
	 * @return the short description of this reference
	 */
	@AutoEscape
	public String getShortDescription();

	/**
	 * Sets the short description of this reference.
	 *
	 * @param shortDescription the short description of this reference
	 */
	public void setShortDescription(String shortDescription);

	/**
	 * Returns the description of this reference.
	 *
	 * @return the description of this reference
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this reference.
	 *
	 * @param description the description of this reference
	 */
	public void setDescription(String description);

	/**
	 * Returns the realization date of this reference.
	 *
	 * @return the realization date of this reference
	 */
	public Date getRealizationDate();

	/**
	 * Sets the realization date of this reference.
	 *
	 * @param realizationDate the realization date of this reference
	 */
	public void setRealizationDate(Date realizationDate);

	/**
	 * Returns the emphasized of this reference.
	 *
	 * @return the emphasized of this reference
	 */
	public boolean getEmphasized();

	/**
	 * Returns <code>true</code> if this reference is emphasized.
	 *
	 * @return <code>true</code> if this reference is emphasized; <code>false</code> otherwise
	 */
	public boolean isEmphasized();

	/**
	 * Sets whether this reference is emphasized.
	 *
	 * @param emphasized the emphasized of this reference
	 */
	public void setEmphasized(boolean emphasized);

	/**
	 * Returns the overlay text of this reference.
	 *
	 * @return the overlay text of this reference
	 */
	@AutoEscape
	public String getOverlayText();

	/**
	 * Sets the overlay text of this reference.
	 *
	 * @param overlayText the overlay text of this reference
	 */
	public void setOverlayText(String overlayText);

	/**
	 * Returns the overlay url of this reference.
	 *
	 * @return the overlay url of this reference
	 */
	@AutoEscape
	public String getOverlayUrl();

	/**
	 * Sets the overlay url of this reference.
	 *
	 * @param overlayUrl the overlay url of this reference
	 */
	public void setOverlayUrl(String overlayUrl);

	/**
	 * Returns the last publish date of this reference.
	 *
	 * @return the last publish date of this reference
	 */
	@Override
	public Date getLastPublishDate();

	/**
	 * Sets the last publish date of this reference.
	 *
	 * @param lastPublishDate the last publish date of this reference
	 */
	@Override
	public void setLastPublishDate(Date lastPublishDate);

	/**
	 * Returns the status of this reference.
	 *
	 * @return the status of this reference
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this reference.
	 *
	 * @param status the status of this reference
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this reference.
	 *
	 * @return the status by user ID of this reference
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this reference.
	 *
	 * @param statusByUserId the status by user ID of this reference
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this reference.
	 *
	 * @return the status by user uuid of this reference
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this reference.
	 *
	 * @param statusByUserUuid the status by user uuid of this reference
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this reference.
	 *
	 * @return the status by user name of this reference
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this reference.
	 *
	 * @param statusByUserName the status by user name of this reference
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this reference.
	 *
	 * @return the status date of this reference
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this reference.
	 *
	 * @param statusDate the status date of this reference
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the trash entry created when this reference was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this reference.
	 *
	 * @return the trash entry created when this reference was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this reference.
	 *
	 * @return the class primary key of the trash entry for this reference
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this reference.
	 *
	 * @return the trash handler for this reference
	 * @deprecated As of 7.0.0, with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this reference is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this reference is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this reference is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this reference is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this reference is approved.
	 *
	 * @return <code>true</code> if this reference is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this reference is denied.
	 *
	 * @return <code>true</code> if this reference is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this reference is a draft.
	 *
	 * @return <code>true</code> if this reference is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this reference is expired.
	 *
	 * @return <code>true</code> if this reference is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this reference is inactive.
	 *
	 * @return <code>true</code> if this reference is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this reference is incomplete.
	 *
	 * @return <code>true</code> if this reference is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this reference is pending.
	 *
	 * @return <code>true</code> if this reference is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this reference is scheduled.
	 *
	 * @return <code>true</code> if this reference is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Reference reference);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Reference> toCacheModel();

	@Override
	public Reference toEscapedModel();

	@Override
	public Reference toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}