/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.webtown.liferay.portlet.reference.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ReferenceResource service. Represents a row in the &quot;ReferenceResource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.webtown.liferay.portlet.reference.model.impl.ReferenceResourceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.webtown.liferay.portlet.reference.model.impl.ReferenceResourceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReferenceResource
 * @see hu.webtown.liferay.portlet.reference.model.impl.ReferenceResourceImpl
 * @see hu.webtown.liferay.portlet.reference.model.impl.ReferenceResourceModelImpl
 * @generated
 */
@ProviderType
public interface ReferenceResourceModel extends BaseModel<ReferenceResource>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reference resource model instance should use the {@link ReferenceResource} interface instead.
	 */

	/**
	 * Returns the primary key of this reference resource.
	 *
	 * @return the primary key of this reference resource
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reference resource.
	 *
	 * @param primaryKey the primary key of this reference resource
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this reference resource.
	 *
	 * @return the uuid of this reference resource
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this reference resource.
	 *
	 * @param uuid the uuid of this reference resource
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the resource prim key of this reference resource.
	 *
	 * @return the resource prim key of this reference resource
	 */
	public long getResourcePrimKey();

	/**
	 * Sets the resource prim key of this reference resource.
	 *
	 * @param resourcePrimKey the resource prim key of this reference resource
	 */
	public void setResourcePrimKey(long resourcePrimKey);

	/**
	 * Returns the group ID of this reference resource.
	 *
	 * @return the group ID of this reference resource
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this reference resource.
	 *
	 * @param groupId the group ID of this reference resource
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this reference resource.
	 *
	 * @return the company ID of this reference resource
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this reference resource.
	 *
	 * @param companyId the company ID of this reference resource
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the reference ID of this reference resource.
	 *
	 * @return the reference ID of this reference resource
	 */
	@AutoEscape
	public String getReferenceId();

	/**
	 * Sets the reference ID of this reference resource.
	 *
	 * @param referenceId the reference ID of this reference resource
	 */
	public void setReferenceId(String referenceId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ReferenceResource referenceResource);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ReferenceResource> toCacheModel();

	@Override
	public ReferenceResource toEscapedModel();

	@Override
	public ReferenceResource toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}