/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.webtown.liferay.portlet.reference.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ReferenceImage service. Represents a row in the &quot;ReferenceImage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.webtown.liferay.portlet.reference.model.impl.ReferenceImageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.webtown.liferay.portlet.reference.model.impl.ReferenceImageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReferenceImage
 * @see hu.webtown.liferay.portlet.reference.model.impl.ReferenceImageImpl
 * @see hu.webtown.liferay.portlet.reference.model.impl.ReferenceImageModelImpl
 * @generated
 */
@ProviderType
public interface ReferenceImageModel extends BaseModel<ReferenceImage>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reference image model instance should use the {@link ReferenceImage} interface instead.
	 */

	/**
	 * Returns the primary key of this reference image.
	 *
	 * @return the primary key of this reference image
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reference image.
	 *
	 * @param primaryKey the primary key of this reference image
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this reference image.
	 *
	 * @return the uuid of this reference image
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this reference image.
	 *
	 * @param uuid the uuid of this reference image
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the reference image ID of this reference image.
	 *
	 * @return the reference image ID of this reference image
	 */
	public long getReferenceImageId();

	/**
	 * Sets the reference image ID of this reference image.
	 *
	 * @param referenceImageId the reference image ID of this reference image
	 */
	public void setReferenceImageId(long referenceImageId);

	/**
	 * Returns the group ID of this reference image.
	 *
	 * @return the group ID of this reference image
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this reference image.
	 *
	 * @param groupId the group ID of this reference image
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this reference image.
	 *
	 * @return the company ID of this reference image
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this reference image.
	 *
	 * @param companyId the company ID of this reference image
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the reference ID of this reference image.
	 *
	 * @return the reference ID of this reference image
	 */
	@AutoEscape
	public String getReferenceId();

	/**
	 * Sets the reference ID of this reference image.
	 *
	 * @param referenceId the reference ID of this reference image
	 */
	public void setReferenceId(String referenceId);

	/**
	 * Returns the version of this reference image.
	 *
	 * @return the version of this reference image
	 */
	public double getVersion();

	/**
	 * Sets the version of this reference image.
	 *
	 * @param version the version of this reference image
	 */
	public void setVersion(double version);

	/**
	 * Returns the image type of this reference image.
	 *
	 * @return the image type of this reference image
	 */
	public int getImageType();

	/**
	 * Sets the image type of this reference image.
	 *
	 * @param imageType the image type of this reference image
	 */
	public void setImageType(int imageType);

	/**
	 * Returns the image of this reference image.
	 *
	 * @return the image of this reference image
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this reference image.
	 *
	 * @param image the image of this reference image
	 */
	public void setImage(String image);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ReferenceImage referenceImage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ReferenceImage> toCacheModel();

	@Override
	public ReferenceImage toEscapedModel();

	@Override
	public ReferenceImage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}