/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.webtown.liferay.portlet.reference.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import hu.webtown.liferay.portlet.reference.model.ReferenceResource;
import hu.webtown.liferay.portlet.reference.model.ReferenceResourceModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ReferenceResource service. Represents a row in the &quot;ReferenceResource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ReferenceResourceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReferenceResourceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReferenceResourceImpl
 * @see ReferenceResource
 * @see ReferenceResourceModel
 * @generated
 */
@ProviderType
public class ReferenceResourceModelImpl extends BaseModelImpl<ReferenceResource>
	implements ReferenceResourceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a reference resource model instance should use the {@link ReferenceResource} interface instead.
	 */
	public static final String TABLE_NAME = "ReferenceResource";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "resourcePrimKey", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "referenceId", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("resourcePrimKey", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("referenceId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table ReferenceResource (uuid_ VARCHAR(75) null,resourcePrimKey LONG not null primary key,groupId LONG,companyId LONG,referenceId VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ReferenceResource";
	public static final String ORDER_BY_JPQL = " ORDER BY referenceResource.resourcePrimKey ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ReferenceResource.resourcePrimKey ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(hu.webtown.liferay.portlet.reference.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.hu.webtown.liferay.portlet.reference.model.ReferenceResource"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(hu.webtown.liferay.portlet.reference.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.hu.webtown.liferay.portlet.reference.model.ReferenceResource"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(hu.webtown.liferay.portlet.reference.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.hu.webtown.liferay.portlet.reference.model.ReferenceResource"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long REFERENCEID_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;
	public static final long RESOURCEPRIMKEY_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(hu.webtown.liferay.portlet.reference.service.util.ServiceProps.get(
				"lock.expiration.time.hu.webtown.liferay.portlet.reference.model.ReferenceResource"));

	public ReferenceResourceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _resourcePrimKey;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setResourcePrimKey(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _resourcePrimKey;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ReferenceResource.class;
	}

	@Override
	public String getModelClassName() {
		return ReferenceResource.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("resourcePrimKey", getResourcePrimKey());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("referenceId", getReferenceId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long resourcePrimKey = (Long)attributes.get("resourcePrimKey");

		if (resourcePrimKey != null) {
			setResourcePrimKey(resourcePrimKey);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		String referenceId = (String)attributes.get("referenceId");

		if (referenceId != null) {
			setReferenceId(referenceId);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getResourcePrimKey() {
		return _resourcePrimKey;
	}

	@Override
	public void setResourcePrimKey(long resourcePrimKey) {
		_resourcePrimKey = resourcePrimKey;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public String getReferenceId() {
		if (_referenceId == null) {
			return "";
		}
		else {
			return _referenceId;
		}
	}

	@Override
	public void setReferenceId(String referenceId) {
		_columnBitmask |= REFERENCEID_COLUMN_BITMASK;

		if (_originalReferenceId == null) {
			_originalReferenceId = _referenceId;
		}

		_referenceId = referenceId;
	}

	public String getOriginalReferenceId() {
		return GetterUtil.getString(_originalReferenceId);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ReferenceResource.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ReferenceResource toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ReferenceResource)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReferenceResourceImpl referenceResourceImpl = new ReferenceResourceImpl();

		referenceResourceImpl.setUuid(getUuid());
		referenceResourceImpl.setResourcePrimKey(getResourcePrimKey());
		referenceResourceImpl.setGroupId(getGroupId());
		referenceResourceImpl.setCompanyId(getCompanyId());
		referenceResourceImpl.setReferenceId(getReferenceId());

		referenceResourceImpl.resetOriginalValues();

		return referenceResourceImpl;
	}

	@Override
	public int compareTo(ReferenceResource referenceResource) {
		long primaryKey = referenceResource.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ReferenceResource)) {
			return false;
		}

		ReferenceResource referenceResource = (ReferenceResource)obj;

		long primaryKey = referenceResource.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ReferenceResourceModelImpl referenceResourceModelImpl = this;

		referenceResourceModelImpl._originalUuid = referenceResourceModelImpl._uuid;

		referenceResourceModelImpl._originalGroupId = referenceResourceModelImpl._groupId;

		referenceResourceModelImpl._setOriginalGroupId = false;

		referenceResourceModelImpl._originalCompanyId = referenceResourceModelImpl._companyId;

		referenceResourceModelImpl._setOriginalCompanyId = false;

		referenceResourceModelImpl._originalReferenceId = referenceResourceModelImpl._referenceId;

		referenceResourceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ReferenceResource> toCacheModel() {
		ReferenceResourceCacheModel referenceResourceCacheModel = new ReferenceResourceCacheModel();

		referenceResourceCacheModel.uuid = getUuid();

		String uuid = referenceResourceCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			referenceResourceCacheModel.uuid = null;
		}

		referenceResourceCacheModel.resourcePrimKey = getResourcePrimKey();

		referenceResourceCacheModel.groupId = getGroupId();

		referenceResourceCacheModel.companyId = getCompanyId();

		referenceResourceCacheModel.referenceId = getReferenceId();

		String referenceId = referenceResourceCacheModel.referenceId;

		if ((referenceId != null) && (referenceId.length() == 0)) {
			referenceResourceCacheModel.referenceId = null;
		}

		return referenceResourceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", resourcePrimKey=");
		sb.append(getResourcePrimKey());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", referenceId=");
		sb.append(getReferenceId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append(
			"hu.webtown.liferay.portlet.reference.model.ReferenceResource");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resourcePrimKey</column-name><column-value><![CDATA[");
		sb.append(getResourcePrimKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>referenceId</column-name><column-value><![CDATA[");
		sb.append(getReferenceId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ReferenceResource.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ReferenceResource.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _resourcePrimKey;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private String _referenceId;
	private String _originalReferenceId;
	private long _columnBitmask;
	private ReferenceResource _escapedModel;
}