/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.webtown.liferay.portlet.reference.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import hu.webtown.liferay.portlet.reference.model.ReferenceImage;
import hu.webtown.liferay.portlet.reference.service.ReferenceImageLocalService;
import hu.webtown.liferay.portlet.reference.service.persistence.ReferenceFinder;
import hu.webtown.liferay.portlet.reference.service.persistence.ReferenceImagePersistence;
import hu.webtown.liferay.portlet.reference.service.persistence.ReferencePersistence;
import hu.webtown.liferay.portlet.reference.service.persistence.ReferenceResourcePersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the reference image local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link hu.webtown.liferay.portlet.reference.service.impl.ReferenceImageLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see hu.webtown.liferay.portlet.reference.service.impl.ReferenceImageLocalServiceImpl
 * @see hu.webtown.liferay.portlet.reference.service.ReferenceImageLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class ReferenceImageLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ReferenceImageLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link hu.webtown.liferay.portlet.reference.service.ReferenceImageLocalServiceUtil} to access the reference image local service.
	 */

	/**
	 * Adds the reference image to the database. Also notifies the appropriate model listeners.
	 *
	 * @param referenceImage the reference image
	 * @return the reference image that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ReferenceImage addReferenceImage(ReferenceImage referenceImage) {
		referenceImage.setNew(true);

		return referenceImagePersistence.update(referenceImage);
	}

	/**
	 * Creates a new reference image with the primary key. Does not add the reference image to the database.
	 *
	 * @param referenceImageId the primary key for the new reference image
	 * @return the new reference image
	 */
	@Override
	@Transactional(enabled = false)
	public ReferenceImage createReferenceImage(long referenceImageId) {
		return referenceImagePersistence.create(referenceImageId);
	}

	/**
	 * Deletes the reference image with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param referenceImageId the primary key of the reference image
	 * @return the reference image that was removed
	 * @throws PortalException if a reference image with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ReferenceImage deleteReferenceImage(long referenceImageId)
		throws PortalException {
		return referenceImagePersistence.remove(referenceImageId);
	}

	/**
	 * Deletes the reference image from the database. Also notifies the appropriate model listeners.
	 *
	 * @param referenceImage the reference image
	 * @return the reference image that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ReferenceImage deleteReferenceImage(ReferenceImage referenceImage) {
		return referenceImagePersistence.remove(referenceImage);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ReferenceImage.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return referenceImagePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link hu.webtown.liferay.portlet.reference.model.impl.ReferenceImageModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return referenceImagePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link hu.webtown.liferay.portlet.reference.model.impl.ReferenceImageModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return referenceImagePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return referenceImagePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return referenceImagePersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public ReferenceImage fetchReferenceImage(long referenceImageId) {
		return referenceImagePersistence.fetchByPrimaryKey(referenceImageId);
	}

	/**
	 * Returns the reference image matching the UUID and group.
	 *
	 * @param uuid the reference image's UUID
	 * @param groupId the primary key of the group
	 * @return the matching reference image, or <code>null</code> if a matching reference image could not be found
	 */
	@Override
	public ReferenceImage fetchReferenceImageByUuidAndGroupId(String uuid,
		long groupId) {
		return referenceImagePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the reference image with the primary key.
	 *
	 * @param referenceImageId the primary key of the reference image
	 * @return the reference image
	 * @throws PortalException if a reference image with the primary key could not be found
	 */
	@Override
	public ReferenceImage getReferenceImage(long referenceImageId)
		throws PortalException {
		return referenceImagePersistence.findByPrimaryKey(referenceImageId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(referenceImageLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ReferenceImage.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("referenceImageId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(referenceImageLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ReferenceImage.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"referenceImageId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(referenceImageLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ReferenceImage.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("referenceImageId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return referenceImageLocalService.deleteReferenceImage((ReferenceImage)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return referenceImagePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the reference images matching the UUID and company.
	 *
	 * @param uuid the UUID of the reference images
	 * @param companyId the primary key of the company
	 * @return the matching reference images, or an empty list if no matches were found
	 */
	@Override
	public List<ReferenceImage> getReferenceImagesByUuidAndCompanyId(
		String uuid, long companyId) {
		return referenceImagePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of reference images matching the UUID and company.
	 *
	 * @param uuid the UUID of the reference images
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of reference images
	 * @param end the upper bound of the range of reference images (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching reference images, or an empty list if no matches were found
	 */
	@Override
	public List<ReferenceImage> getReferenceImagesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<ReferenceImage> orderByComparator) {
		return referenceImagePersistence.findByUuid_C(uuid, companyId, start,
			end, orderByComparator);
	}

	/**
	 * Returns the reference image matching the UUID and group.
	 *
	 * @param uuid the reference image's UUID
	 * @param groupId the primary key of the group
	 * @return the matching reference image
	 * @throws PortalException if a matching reference image could not be found
	 */
	@Override
	public ReferenceImage getReferenceImageByUuidAndGroupId(String uuid,
		long groupId) throws PortalException {
		return referenceImagePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the reference images.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link hu.webtown.liferay.portlet.reference.model.impl.ReferenceImageModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of reference images
	 * @param end the upper bound of the range of reference images (not inclusive)
	 * @return the range of reference images
	 */
	@Override
	public List<ReferenceImage> getReferenceImages(int start, int end) {
		return referenceImagePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of reference images.
	 *
	 * @return the number of reference images
	 */
	@Override
	public int getReferenceImagesCount() {
		return referenceImagePersistence.countAll();
	}

	/**
	 * Updates the reference image in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param referenceImage the reference image
	 * @return the reference image that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ReferenceImage updateReferenceImage(ReferenceImage referenceImage) {
		return referenceImagePersistence.update(referenceImage);
	}

	/**
	 * Returns the reference local service.
	 *
	 * @return the reference local service
	 */
	public hu.webtown.liferay.portlet.reference.service.ReferenceLocalService getReferenceLocalService() {
		return referenceLocalService;
	}

	/**
	 * Sets the reference local service.
	 *
	 * @param referenceLocalService the reference local service
	 */
	public void setReferenceLocalService(
		hu.webtown.liferay.portlet.reference.service.ReferenceLocalService referenceLocalService) {
		this.referenceLocalService = referenceLocalService;
	}

	/**
	 * Returns the reference persistence.
	 *
	 * @return the reference persistence
	 */
	public ReferencePersistence getReferencePersistence() {
		return referencePersistence;
	}

	/**
	 * Sets the reference persistence.
	 *
	 * @param referencePersistence the reference persistence
	 */
	public void setReferencePersistence(
		ReferencePersistence referencePersistence) {
		this.referencePersistence = referencePersistence;
	}

	/**
	 * Returns the reference finder.
	 *
	 * @return the reference finder
	 */
	public ReferenceFinder getReferenceFinder() {
		return referenceFinder;
	}

	/**
	 * Sets the reference finder.
	 *
	 * @param referenceFinder the reference finder
	 */
	public void setReferenceFinder(ReferenceFinder referenceFinder) {
		this.referenceFinder = referenceFinder;
	}

	/**
	 * Returns the reference image local service.
	 *
	 * @return the reference image local service
	 */
	public ReferenceImageLocalService getReferenceImageLocalService() {
		return referenceImageLocalService;
	}

	/**
	 * Sets the reference image local service.
	 *
	 * @param referenceImageLocalService the reference image local service
	 */
	public void setReferenceImageLocalService(
		ReferenceImageLocalService referenceImageLocalService) {
		this.referenceImageLocalService = referenceImageLocalService;
	}

	/**
	 * Returns the reference image persistence.
	 *
	 * @return the reference image persistence
	 */
	public ReferenceImagePersistence getReferenceImagePersistence() {
		return referenceImagePersistence;
	}

	/**
	 * Sets the reference image persistence.
	 *
	 * @param referenceImagePersistence the reference image persistence
	 */
	public void setReferenceImagePersistence(
		ReferenceImagePersistence referenceImagePersistence) {
		this.referenceImagePersistence = referenceImagePersistence;
	}

	/**
	 * Returns the reference resource local service.
	 *
	 * @return the reference resource local service
	 */
	public hu.webtown.liferay.portlet.reference.service.ReferenceResourceLocalService getReferenceResourceLocalService() {
		return referenceResourceLocalService;
	}

	/**
	 * Sets the reference resource local service.
	 *
	 * @param referenceResourceLocalService the reference resource local service
	 */
	public void setReferenceResourceLocalService(
		hu.webtown.liferay.portlet.reference.service.ReferenceResourceLocalService referenceResourceLocalService) {
		this.referenceResourceLocalService = referenceResourceLocalService;
	}

	/**
	 * Returns the reference resource persistence.
	 *
	 * @return the reference resource persistence
	 */
	public ReferenceResourcePersistence getReferenceResourcePersistence() {
		return referenceResourcePersistence;
	}

	/**
	 * Sets the reference resource persistence.
	 *
	 * @param referenceResourcePersistence the reference resource persistence
	 */
	public void setReferenceResourcePersistence(
		ReferenceResourcePersistence referenceResourcePersistence) {
		this.referenceResourcePersistence = referenceResourcePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("hu.webtown.liferay.portlet.reference.model.ReferenceImage",
			referenceImageLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"hu.webtown.liferay.portlet.reference.model.ReferenceImage");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ReferenceImageLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ReferenceImage.class;
	}

	protected String getModelClassName() {
		return ReferenceImage.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = referenceImagePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = hu.webtown.liferay.portlet.reference.service.ReferenceLocalService.class)
	protected hu.webtown.liferay.portlet.reference.service.ReferenceLocalService referenceLocalService;
	@BeanReference(type = ReferencePersistence.class)
	protected ReferencePersistence referencePersistence;
	@BeanReference(type = ReferenceFinder.class)
	protected ReferenceFinder referenceFinder;
	@BeanReference(type = ReferenceImageLocalService.class)
	protected ReferenceImageLocalService referenceImageLocalService;
	@BeanReference(type = ReferenceImagePersistence.class)
	protected ReferenceImagePersistence referenceImagePersistence;
	@BeanReference(type = hu.webtown.liferay.portlet.reference.service.ReferenceResourceLocalService.class)
	protected hu.webtown.liferay.portlet.reference.service.ReferenceResourceLocalService referenceResourceLocalService;
	@BeanReference(type = ReferenceResourcePersistence.class)
	protected ReferenceResourcePersistence referenceResourcePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}